spring:
  application.name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          url-expression: "'lb://'+serviceId"
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
      discovery:
        filter: "metadata.labels['s1p']"
        discovery-server-url: "http://spring-cloud-kubernetes-discoveryserver.default.svc.cluster.local:80"


server.port: 8080
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    info:
      enabled: true